In [1]:
import numpy as np

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
#create a DataFrame from a Numpy array
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2,3))


In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2,3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
range_array = np.arange(0, 10, 2)

In [31]:
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0, 10, size=(3,5))

In [33]:
random_array


array([[9, 7, 1, 9, 3],
       [1, 9, 6, 8, 0],
       [8, 7, 0, 8, 3]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [39]:
random_array2 = np.random.random((5,3))

In [40]:
random_array2.shape

(5, 3)

In [41]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.91217899, 0.18371193, 0.79326795],
       [0.86486945, 0.59886525, 0.7912675 ],
       [0.93024156, 0.34807778, 0.027833  ],
       [0.40288938, 0.86328801, 0.18335891],
       [0.06943086, 0.9600391 , 0.23250411]])

In [51]:
#pseudo random numbers
#seed locks in the random integers
seed = np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5,3))

In [50]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [58]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [60]:
random_array5 = np.random.random((5,3))
random_array5

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])

## 3. Viewing Arrays and matrices

In [61]:
a1


array([1, 2, 3])

In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a1[0]

1

In [65]:
a2[0]

array([1. , 2. , 3.3])

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [69]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 0, 9, 8, 2],
         [0, 5, 5, 0, 9],
         [0, 8, 4, 5, 1],
         [4, 0, 7, 2, 0]],

        [[3, 9, 8, 3, 7],
         [1, 0, 1, 4, 6],
         [1, 0, 1, 0, 1],
         [8, 4, 1, 6, 8]],

        [[5, 2, 4, 7, 4],
         [1, 2, 8, 5, 2],
         [9, 6, 2, 5, 7],
         [7, 5, 5, 6, 0]]],


       [[[6, 4, 6, 2, 6],
         [8, 7, 0, 5, 8],
         [9, 7, 7, 6, 2],
         [5, 6, 1, 9, 3]],

        [[4, 0, 3, 5, 6],
         [4, 0, 4, 1, 5],
         [2, 4, 8, 7, 5],
         [7, 5, 3, 7, 6]],

        [[2, 3, 1, 1, 8],
         [4, 2, 1, 7, 0],
         [8, 8, 1, 2, 3],
         [0, 1, 1, 5, 5]]]])

In [70]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [72]:
# Get the first 4 numbers of the inner most array
a4[:, :, :, :4]

array([[[[0, 0, 9, 8],
         [0, 5, 5, 0],
         [0, 8, 4, 5],
         [4, 0, 7, 2]],

        [[3, 9, 8, 3],
         [1, 0, 1, 4],
         [1, 0, 1, 0],
         [8, 4, 1, 6]],

        [[5, 2, 4, 7],
         [1, 2, 8, 5],
         [9, 6, 2, 5],
         [7, 5, 5, 6]]],


       [[[6, 4, 6, 2],
         [8, 7, 0, 5],
         [9, 7, 7, 6],
         [5, 6, 1, 9]],

        [[4, 0, 3, 5],
         [4, 0, 4, 1],
         [2, 4, 8, 7],
         [7, 5, 3, 7]],

        [[2, 3, 1, 1],
         [4, 2, 1, 7],
         [8, 8, 1, 2],
         [0, 1, 1, 5]]]])

## 4. Manipulating & Comparing Arrays

In [73]:
a1

array([1, 2, 3])

In [74]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [75]:
a1 + ones

array([2., 3., 4.])

In [76]:
a1 - ones

array([0., 1., 2.])

In [77]:
a1 * ones

array([1., 2., 3.])

In [78]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [79]:
# How to reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [80]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [82]:
# Floor Division
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])